// Definitional guide (GEO surface): answers "what is AI slop" in the exact
// phrasing people type into Google and ask AI assistants. Owns the term that
// the product is named after. Article + FAQPage JSON-LD so answer engines can
// quote it accurately.
import type { Metadata } from "next";
import Link from "next/link";
import { env } from "@/lib/env";
import { SANS, MONO, card } from "@/components/slopdar/ui";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import Faq from "@/components/Faq";

export const metadata: Metadata = {
  title: "What is AI slop? Meaning, examples, and how to spot it",
  description:
    "AI slop is low-effort, mass-produced AI-generated content published without human care. What the term means, where it came from, and how to spot slop websites.",
  alternates: { canonical: "/guide/what-is-ai-slop" },
  openGraph: {
    title: "What is AI slop?",
    description: "The meaning of AI slop, where the term came from, and how to spot it in the wild.",
    url: "/guide/what-is-ai-slop",
    type: "article",
  },
};

const KINDS = [
  {
    t: "Text slop",
    d: "Articles, product descriptions and social posts generated in bulk and published unread. The tells: buzzwords doing the work of ideas ('elevate', 'seamless', 'unlock'), sentences that could describe anything, and confident claims with no specifics behind them.",
  },
  {
    t: "Image and video slop",
    d: "The six-fingered hands, the melting text, the uncanny stock-photo people who don't exist. Generated visuals flooding feeds because producing a thousand of them costs less than licensing one real photograph.",
  },
  {
    t: "Website slop",
    d: "Entire sites generated by prompt and deployed unedited: the same gradient hero, the same three feature cards, the same default components, sometimes with 'lorem ipsum' still in the footer. This is the kind Slopdar measures.",
  },
];

const FAQ = [
  {
    q: "What does AI slop mean?",
    a: "AI slop is low-effort, mass-produced content generated by AI and published with little or no human review. The defining feature isn't that AI was used; it's that nobody cared enough to check, edit or improve the output before shipping it. Slop is to AI content what spam is to email.",
  },
  {
    q: "Where did the term AI slop come from?",
    a: "It grew out of internet forums as generated content started flooding feeds, and took off in 2024 when writers and developers needed a word for the tide of unreviewed AI output. 'Slop' stuck because it captures the texture: mass-produced, indistinguishable, poured out rather than made.",
  },
  {
    q: "Is all AI-generated content slop?",
    a: "No. Slop is defined by absence of care, not presence of AI. An article drafted with AI, then fact-checked, rewritten and edited by a person isn't slop. The same article published straight from the chat window is. Tools don't make slop; publishing without judgment does.",
  },
  {
    q: "What is a Slop Score?",
    a: "A Slop Score is Slopdar's 0 to 100 estimate of how much a website looks vibe-coded or AI-generated. It runs ~50 checks for tells like builder fingerprints, untouched default components, AI writing patterns and leftover placeholders, then shows the evidence. Higher score, more tells found. It measures signals, not proof.",
  },
  {
    q: "How do I avoid publishing AI slop?",
    a: "Use AI as a collaborator, not a vending machine. Rewrite the copy in your own voice, replace default components and layouts with actual decisions, fill in real metadata, and delete every section that could belong to any other product. If you can't say why an element is there, that's the part to fix.",
  },
];

export default function WhatIsAiSlopPage() {
  const base = env.APP_URL.replace(/\/$/, "");
  const ld = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        headline: "What is AI slop? Meaning, examples, and how to spot it",
        description: metadata.description,
        author: { "@type": "Organization", name: "Slopdar", url: base },
        publisher: { "@type": "Organization", name: "Slopdar", url: base },
        datePublished: "2026-07-30",
        mainEntityOfPage: `${base}/guide/what-is-ai-slop`,
      },
      {
        "@type": "FAQPage",
        mainEntity: FAQ.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
      },
    ],
  };
  const eyebrow = { fontFamily: MONO, fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase", color: "var(--mut)" } as const;
  const h2 = { fontWeight: 900, fontSize: 24, letterSpacing: "-.02em", margin: "34px 0 0" } as const;
  const p = { fontSize: 15, lineHeight: 1.65, color: "var(--ink2)", margin: "12px 0 0" } as const;

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", fontFamily: SANS, color: "var(--ink)", background: "var(--bg)" }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} />
      <SiteHeader />

      <main style={{ flex: "1 0 auto", maxWidth: 760, margin: "0 auto", padding: "46px 28px 30px", width: "100%" }}>
        <div style={eyebrow}>The field guide</div>
        <h1 style={{ fontWeight: 900, fontSize: "clamp(32px,5.4vw,52px)", letterSpacing: "-.035em", margin: "8px 0 0", lineHeight: 1.02 }}>
          What is AI slop?
        </h1>
        <p style={{ ...p, fontSize: 16, marginTop: 14 }}>
          <span style={{ color: "var(--ink)", fontWeight: 700 }}>AI slop</span> is low-effort, mass-produced content generated
          by AI and published with little or no human review. The word that matters in that definition isn&apos;t
          &quot;AI&quot;; it&apos;s &quot;low-effort&quot;. Slop is what happens when generating something became so cheap that
          checking it started to feel expensive.
        </p>

        <h2 style={h2}>Slop is to AI what spam is to email</h2>
        <p style={p}>
          Email didn&apos;t create junk mail; it made junk mail free to send, and spam was born. AI didn&apos;t create lazy
          content; it made lazy content free to produce, and slop was born. The term grew out of internet forums and took off
          in 2024, when generated articles, images and entire websites started flooding feeds faster than anyone could read
          them. People needed a word for &quot;technically content, but nobody was home when it was made&quot;, and slop fit.
        </p>

        <div style={{ ...eyebrow, marginTop: 36, marginBottom: 14 }}>The three kinds</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          {KINDS.map((k, i) => (
            <div key={k.t} style={{ ...card, padding: "22px 24px", display: "flex", gap: 18, alignItems: "flex-start" }}>
              <span style={{ fontWeight: 900, fontSize: 26, color: "var(--brand)", lineHeight: 1.2, flexShrink: 0, width: 34 }}>
                {String(i + 1).padStart(2, "0")}
              </span>
              <div>
                <h3 style={{ fontWeight: 900, fontSize: 18, margin: 0 }}>{k.t}</h3>
                <p style={{ fontSize: 14.5, lineHeight: 1.6, color: "var(--ink2)", margin: "8px 0 0" }}>{k.d}</p>
              </div>
            </div>
          ))}
        </div>

        <h2 style={h2}>What slop is not</h2>
        <p style={p}>
          Slop is not &quot;anything made with AI&quot;. A developer who drafts with AI, then rewrites the copy, swaps the
          default components, and deletes the generic sections has made a website; the tool is invisible because the
          craftsmanship hid it. The same output shipped straight from the chat window is slop. The dividing line is whether a
          human made decisions after the machine stopped. That&apos;s also why calling something slop is an accusation about
          effort, not about tools.
        </p>

        <h2 style={h2}>How to spot website slop</h2>
        <p style={p}>
          Slop websites give themselves away through consistent tells: builder fingerprints left in the source code, untouched
          default component stacks, AI writing patterns in the copy, leftover placeholders, and the same template layout every
          time. We keep a full checklist in{" "}
          <Link href="/guide/how-to-tell-if-a-website-is-ai-generated" className="h-brandtext" style={{ color: "var(--brand)", fontWeight: 700 }}>
            how to tell if a website is AI-generated
          </Link>
          , with instructions for checking each sign by hand. Most of them come from{" "}
          <Link href="/guide/what-is-vibe-coding" className="h-brandtext" style={{ color: "var(--brand)", fontWeight: 700 }}>
            vibe coding
          </Link>{" "}
          left unedited: the tools aren&apos;t the problem, but their defaults are loud.
        </p>

        <div style={{ marginTop: 24, ...card, borderRadius: 18, padding: "24px 26px", boxShadow: "0 6px 0 rgba(0,0,0,.1)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ fontSize: 22 }}>📡</span>
            <h2 style={{ fontWeight: 900, fontSize: 19, letterSpacing: "-.01em", margin: 0 }}>Measuring it: the Slop Score</h2>
          </div>
          <p style={{ fontSize: 14.5, lineHeight: 1.6, color: "var(--ink2)", margin: "11px 0 0" }}>
            Slopdar turns this definition into a number: paste a URL and ~50 weighted checks estimate how much a site looks
            vibe-coded or AI-generated, from 0 (Hand-Crafted) to 100 (Pure Slop), with the evidence listed so you can argue
            with it. It&apos;s signals, not proof: a high score means the site looks templated, not that no human was ever
            involved.{" "}
            <Link href="/how-it-works" className="h-brandtext" style={{ color: "var(--brand)", fontWeight: 700 }}>Here&apos;s exactly how the scoring works</Link>.
          </p>
        </div>

        <div style={{ ...eyebrow, marginTop: 34, marginBottom: 14 }}>Questions people ask</div>
        <Faq items={FAQ} />

        <div style={{ marginTop: 26 }}>
          <Link href="/" style={{ display: "inline-block", background: "var(--brand)", color: "#fff", border: "2px solid var(--ink)", borderRadius: 12, fontWeight: 900, fontSize: 15, padding: "14px 26px", textDecoration: "none", boxShadow: "0 5px 0 rgba(0,0,0,.14)" }}>
            Get a Slop Score in 10 seconds →
          </Link>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
