// 🔧 Leftover junk — placeholder content nobody bothered to replace.
import type { SignalRule } from "../types";
import { rawHtml, snippet, visibleText } from "./util";

export const leftoverSignals: SignalRule[] = [
  {
    id: "leftover.lorem",
    category: "leftover",
    weight: 22,
    label: "Lorem ipsum placeholder text",
    description: "Untouched lorem-ipsum filler text is still on the page.",
    test: (ctx) => (visibleText(ctx).toLowerCase().includes("lorem ipsum") ? { evidence: "lorem ipsum" } : null),
  },
  {
    id: "leftover.your-company",
    category: "leftover",
    weight: 16,
    label: "Placeholder brand name",
    description: 'Template placeholders like "Your Company" / "Acme" remain.',
    test: (ctx) => {
      const text = visibleText(ctx).toLowerCase();
      const m = text.match(/your company|your brand|acme(?:\s+(?:inc|corp|co))?|company name/);
      return m ? { evidence: snippet(m[0]) } : null;
    },
  },
  {
    id: "leftover.create-next-app",
    category: "leftover",
    weight: 24,
    label: 'Default "Create Next App" metadata',
    description: "The page title/description is the untouched Next.js default.",
    test: (ctx) => {
      const title = (ctx.$("title").text() || "").toLowerCase();
      const desc = (ctx.$('meta[name="description"]').attr("content") || "").toLowerCase();
      if (title.includes("create next app") || desc.includes("generated by create next app")) {
        return { evidence: "Create Next App default metadata" };
      }
      return null;
    },
  },
  {
    id: "leftover.placeholder-links",
    category: "leftover",
    weight: 10,
    label: "Dead placeholder links",
    description: 'Many links still point to "#" or example.com.',
    test: (ctx) => {
      const $ = ctx.$;
      const anchors = $("a[href]");
      if (anchors.length < 5) return null;
      let dead = 0;
      anchors.each((_, el) => {
        const href = ($(el).attr("href") || "").trim().toLowerCase();
        if (href === "#" || href === "" || href.includes("example.com")) dead++;
      });
      return dead >= 4 ? { evidence: `${dead} dead/placeholder links` } : null;
    },
  },
  {
    id: "leftover.placeholder-images",
    category: "leftover",
    weight: 8,
    label: "Placeholder images",
    description: "Stock placeholder image services (placehold.co, via.placeholder).",
    test: (ctx) => {
      const html = rawHtml(ctx);
      if (html.includes("placehold.co") || html.includes("via.placeholder") || html.includes("placekitten")) {
        return { evidence: "placeholder image service" };
      }
      return null;
    },
  },
];
