// 🔧 Leftover junk — placeholder content nobody bothered to replace.
import type { SignalRule } from "../types";
import { rawHtml, snippet, visibleText } from "./util";

export const leftoverSignals: SignalRule[] = [
  {
    id: "leftover.lorem",
    category: "leftover",
    weight: 22,
    label: "Lorem ipsum placeholder text",
    description: "Untouched lorem-ipsum filler text is still on the page.",
    test: (ctx) => (visibleText(ctx).toLowerCase().includes("lorem ipsum") ? { evidence: "lorem ipsum" } : null),
  },
  {
    id: "leftover.your-company",
    category: "leftover",
    weight: 16,
    label: "Placeholder brand name",
    description: 'Template placeholders like "Your Company" / "Acme" remain.',
    test: (ctx) => {
      const text = visibleText(ctx).toLowerCase();
      const m = text.match(/your company|your brand|acme(?:\s+(?:inc|corp|co))?|company name/);
      return m ? { evidence: snippet(m[0]) } : null;
    },
  },
  {
    id: "leftover.create-next-app",
    category: "leftover",
    weight: 24,
    label: 'Default "Create Next App" metadata',
    description: "The page title/description is the untouched Next.js default.",
    test: (ctx) => {
      const title = (ctx.$("title").text() || "").toLowerCase();
      const desc = (ctx.$('meta[name="description"]').attr("content") || "").toLowerCase();
      if (title.includes("create next app") || desc.includes("generated by create next app")) {
        return { evidence: "Create Next App default metadata" };
      }
      return null;
    },
  },
  {
    id: "leftover.placeholder-links",
    category: "leftover",
    weight: 10,
    label: "Dead placeholder links",
    description: 'Many links still point to "#" or example.com.',
    test: (ctx) => {
      const $ = ctx.$;
      const anchors = $("a[href]");
      if (anchors.length < 5) return null;
      let dead = 0;
      anchors.each((_, el) => {
        const href = ($(el).attr("href") || "").trim().toLowerCase();
        if (href === "#" || href === "" || href.includes("example.com")) dead++;
      });
      return dead >= 4 ? { evidence: `${dead} dead/placeholder links` } : null;
    },
  },
  {
    id: "leftover.placeholder-images",
    category: "leftover",
    weight: 8,
    label: "Placeholder images",
    description: "Stock placeholder image services (placehold.co, via.placeholder).",
    test: (ctx) => {
      const html = rawHtml(ctx);
      if (html.includes("placehold.co") || html.includes("via.placeholder") || html.includes("placekitten")) {
        return { evidence: "placeholder image service" };
      }
      return null;
    },
  },

  // ── Tier A: leftover AI artifacts (near-proof; weighted high) ─────────────
  {
    id: "leftover.ai-citation-tokens",
    category: "leftover",
    weight: 35,
    label: "Leftover AI citation tokens",
    description: "Tokens that AI assistants inject (oaicite / contentReference) were left in the page.",
    test: (ctx) => {
      const html = rawHtml(ctx);
      const tokens = ["oaicite", "contentreference", "utm_source=chatgpt.com", "turn0search", "turn0news"];
      const hit = tokens.find((t) => html.includes(t));
      return hit ? { evidence: hit } : null;
    },
  },
  {
    id: "leftover.assistant-phrases",
    category: "leftover",
    weight: 30,
    label: "Chatbot reply left in the copy",
    description: 'Telltale assistant phrasing (e.g. "as an AI language model") is sitting in the visible text.',
    test: (ctx) => {
      const text = visibleText(ctx).toLowerCase();
      const phrases = [
        "as an ai language model",
        "as a large language model",
        "as an ai assistant",
        "i'm sorry, but i can't",
        "i cannot fulfill that",
        "i hope this helps",
        "i can't browse the internet",
        "my knowledge cutoff",
        "i'm just an ai",
      ];
      const hit = phrases.find((p) => text.includes(p));
      return hit ? { evidence: snippet(hit) } : null;
    },
  },
  {
    id: "leftover.template-placeholders",
    category: "leftover",
    weight: 16,
    label: "Unfilled template placeholders",
    description: 'Bracketed template placeholders (like "[Your Company]") were never replaced.',
    test: (ctx) => {
      const text = visibleText(ctx);
      const m = text.match(
        /\[(?:your company|your name|insert[^\]]{0,30}|product name|company name|email|description|address)\]|tagline goes here|your_api_key|replace this (?:text|with)/i,
      );
      return m ? { evidence: snippet(m[0]) } : null;
    },
  },
  {
    id: "leftover.unrendered-markdown",
    category: "leftover",
    weight: 12,
    label: "Raw markdown shown as text",
    description: "Markdown syntax is visible on the page instead of being rendered.",
    test: (ctx) => {
      const text = visibleText(ctx);
      if (/\*\*[^*\n]{2,80}\*\*/.test(text) || /\]\(https?:\/\//.test(text)) {
        return { evidence: "literal markdown in visible text" };
      }
      return null;
    },
  },
];
